### ISSUE TITLE
[Feature Request] Choices.txt for AMUMSS

### ISSUE THREAD

**Issue by DeathWrench** [MetaIdea/NMS_AUTO_MOD_BUILDER_AND_UPDATER_SCRIPT_SYSTEM#3]
I was wondering if there would be a way to remember individual choices through a text file. For example when AMUMSS asks your choices for combining mods or what not, you can put them into the text file and it will remember those choices. I didn't want to touch the .bat directly since I could easily mess things up poking around in there. If there's already documentation on how to do this and I just missed it, my apologies.

**Comment by HolterPhylo** [comment]
No problem,

That is why 'BUILDMOD_AUTO.bat' exist!!!  
Change whatever OPTION you want between lines 12 and 30 (currently) and use it INSTEAD of BUILDMOD.bat (it calls BUILDMOD.BAT for you)
Have a look at 'README - OPTIONS DEFINITIONS.txt' for the available choices.

AMUMSS will NEVER change BUILDMOD_AUTO.bat when updating (unless a new OPTION was introduced).
If you mess the file up, you can deleted it and AMUMSS will re-create it on the next run

Hope that answers your question

**Comment by DeathWrench** [comment]
Ahhh, sweet! It indeed does. Thanks for your time and explanation. :D

**Comment by HolterPhylo** [comment]
Those are the types when 'CombineModPak' is 'Y' or you answer 'Y' yourself.

For 'CombinedModType', the valid choices are:

- -CombinedModType ASK --(default)
- -CombinedModType 1   --GENERIC COMBINED MOD PAK + current DATE-TIME suffix
- -CombinedModType 2   --DISTINCT COMBINED MOD PAK with a NUMERIC suffix
- -CombinedModType 3   --COMPOSITE-NAME COMBINED MOD PAK like Mod1+Mod2+Mod3.pak

as shown in 'README - OPTIONS DEFINITIONS.txt'
